# Generated by Django 3.1.2 on 2021-02-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email_Address', models.EmailField(max_length=250)),
                ('Phone_Number', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
