# Generated by Django 3.1.2 on 2021-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
    ]
